[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_APP_URL = "https://karaf.fr"


[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  timeout = 26

[functions."scheduled-notifications"]
  schedule = "0 * * * *"
